# Generated by Django 5.1.7 on 2025-03-09 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização')),
                ('minimum_stock', models.PositiveIntegerField(default=0, verbose_name='Estoque Mínimo')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_stock', to='products.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Estoque de Manutenção',
                'verbose_name_plural': 'Estoques de Manutenção',
            },
        ),
    ]
